//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyMaQR_v2.Models
{
    using System;
    using System.Collections.Generic;
    using QuanLyMaQR_v2.Controllers;
    
    public partial class ListProduct
    {
        public int STT { get; set; }
        public string ProductID { get; set; }
        public string ProductType { get; set; }
        public string ProductName { get; set; }
    }
}
